[project]
name = "100knocks-preprocess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "imblearn>=0.0",
    "ipykernel>=7.2.0",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "sqlalchemy>=2.0.46",
]
